IFLiveShows/IFLiveShows/Models/ErrorViewModel.cs
using System;

namespace IFLiveShows.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

IFLiveShows/IFLiveShows/Models/Live.cs
using System;
namespace IFLiveShows.Models
{
    public class Live
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Date { get; set; }
        public string Venue { get; set; }
        public string TicketUrl { get; set; }
        public string ImageUrl { get; set; }
        public string MapsUrl { get; set; }
        public Live()
        {
        }
    }
}

IFLiveShows/IFLiveShows/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using IFLiveShows.Models;

namespace IFLiveShows.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

IFLiveShows/IFLiveShows/Controllers/LiveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IFLiveShows.Data;
using IFLiveShows.Models;
using Microsoft.AspNetCore.Authorization;

namespace IFLiveShows.Controllers
{
    public class LiveController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LiveController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Live
        public async Task<IActionResult> Index()
        {
            return View(await _context.Live.ToListAsync());
        }

        // GET: Live/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var live = await _context.Live
                .FirstOrDefaultAsync(m => m.Id == id);
            if (live == null)
            {
                return NotFound();
            }

            return View(live);
        }

        // GET: Live/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Live/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Date,Venue,TicketUrl,ImageUrl,MapsUrl")] Live live)
        {
            if (ModelState.IsValid)
            {
                _context.Add(live);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(live);
        }

        // GET: Live/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var live = await _context.Live.FindAsync(id);
            if (live == null)
            {
                return NotFound();
            }
            return View(live);
        }

        // POST: Live/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Date,Venue,TicketUrl,ImageUrl,MapsUrl")] Live live)
        {
            if (id != live.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(live);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LiveExists(live.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(live);
        }

        // GET: Live/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var live = await _context.Live
                .FirstOrDefaultAsync(m => m.Id == id);
            if (live == null)
            {
                return NotFound();
            }

            return View(live);
        }

        // POST: Live/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var live = await _context.Live.FindAsync(id);
            _context.Live.Remove(live);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LiveExists(int id)
        {
            return _context.Live.Any(e => e.Id == id);
        }
    }
}

IFLiveShows/IFLiveShows/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Illusion Force's Live Schedule</h1>
    <p>Your one-stop shop for IF Lives</p>
</div>

IFLiveShows/IFLiveShows/Views/Live/Create.cshtml
@model IFLiveShows.Models.Live

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Live</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Venue" class="control-label"></label>
                <input asp-for="Venue" class="form-control" />
                <span asp-validation-for="Venue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TicketUrl" class="control-label"></label>
                <input asp-for="TicketUrl" class="form-control" />
                <span asp-validation-for="TicketUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MapsUrl" class="control-label"></label>
                <input asp-for="MapsUrl" class="form-control" />
                <span asp-validation-for="MapsUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

IFLiveShows/IFLiveShows/Views/Live/Delete.cshtml
@model IFLiveShows.Models.Live

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Live</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Venue)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Venue)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TicketUrl)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TicketUrl)
        </dd>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MapsUrl)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

IFLiveShows/IFLiveShows/Views/Live/Details.cshtml
@model IFLiveShows.Models.Live

@{
    ViewData["Title"] = "Details";
}


<h1>Details</h1>

<div>
    <h4>Live</h4>
    <hr />
    <dl class="row">

        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Venue)
        </dd>

        <dd class="col-sm-10">
            <a href="@Html.DisplayFor(model => model.TicketUrl)"><h4>チケット</h4></a>
        </dd>
        <dd class="col-sm-10">
            <img src="@Html.DisplayFor(model => model.ImageUrl)" width="600" height="450"></img>
        </dd>
        <dd class="col-sm-10">
            <iframe src="@Html.DisplayFor(model => model.MapsUrl)" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        </dd>
    </dl>
</divstyle="width:>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

IFLiveShows/IFLiveShows/Views/Live/Edit.cshtml
@model IFLiveShows.Models.Live

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Live</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Venue" class="control-label"></label>
                <input asp-for="Venue" class="form-control" />
                <span asp-validation-for="Venue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TicketUrl" class="control-label"></label>
                <input asp-for="TicketUrl" class="form-control" />
                <span asp-validation-for="TicketUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MapsUrl" class="control-label"></label>
                <input asp-for="MapsUrl" class="form-control" />
                <span asp-validation-for="MapsUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

IFLiveShows/IFLiveShows/Views/Live/Index.cshtml
@model IEnumerable<IFLiveShows.Models.Live>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

IFLiveShows/IFLiveShows/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IFLiveShows</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IFLiveShows</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Live" asp-action="Index">Shows</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - IFLiveShows - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>